Активация пользователя через e-mail
krlvn/codeBusters pull request #21
Opened 2022-10-11 13:53 UTC by py0trandreev

Активация по e-mail

2022-10-11 14:21 UTC, rateterin commented on app/config/settings.py
> +EMAIL_USE_TLS=bool(strtobool(os.getenv('EMAIL_USE_TLS', 'False')))
такие штуки можно реализовать так:
DEBUG = os.getenv("DEBUG", default="false").lower() == "true"

2022-10-11 14:31 UTC, rateterin commented on app/mainapp/urls.py
> +
Зачем тут пустая строка?
Может код хотел вставить?

2022-10-11 14:35 UTC, rateterin commented on app/userapp/views.py
> +
Зачем столько-то?

2022-10-11 14:37 UTC, rateterin requested changes

2022-10-11 14:37 UTC, rateterin commented on app/config/settings.py
> +EMAIL_PORT=int(os.getenv('EMAIL_PORT', '465'))
var1=1 - так плохо
var1 = 1 - так гуд
поправь, пожалуйста

2022-10-11 14:43 UTC, py0trandreev commented on app/mainapp/urls.py
> +from django.urls import path, include
Удалил лишний импорт

2022-10-11 14:44 UTC, py0trandreev commented on app/mainapp/urls.py
> +
Хотел по началу, потом надобность отпала. Удалил лишнюю строку.

2022-10-11 14:48 UTC, py0trandreev commented on app/config/settings.py
> +EMAIL_PORT=int(os.getenv('EMAIL_PORT', '465'))
Исправил

2022-10-11 14:48 UTC, py0trandreev commented on app/userapp/views.py
> +
удалил

2022-10-11 16:54 UTC, rateterin approved these changes

2022-10-14 08:13 UTC, Chamortsev commented on app/mainapp/urls.py
> +
Вообще PEP8, на сколько помню предполагает последнюю строчку делать пустой.
По крайней мере PyCharm  всегда об этом предупреждает.

2022-10-14 08:20 UTC, Chamortsev commented on app/userapp/utils.py
> +from lib2to3.pgen2.pgen import generate_grammar
Не увидел где используется данная библиотека. 
Она точно нужна?

2022-10-14 12:11 UTC, py0trandreev commented on app/userapp/utils.py
> +from lib2to3.pgen2.pgen import generate_grammar
Удалил лишнюю библиотеку.

2022-10-14 12:42 UTC, Chamortsev approved these changes
Вроде все хорошо.

2022-10-14 13:07 UTC, merged