Dev test02
krlvn/codeBusters pull request #88
Opened 2022-11-13 20:23 UTC by py0trandreev

Тесты проекта

2022-11-13 20:49 UTC, chamorsev commented on tests/test_models.py
> +
Зачем столько пробелов?

2022-11-14 14:21 UTC, rateterin requested changes
в app/mainapp/views.py добавь, пожалуйста в конец файла пустую строку

2022-11-14 14:21 UTC, rateterin commented on tests/test_views.py
> +
Лишняя пустая строка

2022-11-14 14:21 UTC, rateterin commented on tests/test_views.py
> +
Лишняя пустая строка

2022-11-14 14:21 UTC, rateterin commented on tests/test_views.py
> +
Убрать все пробелы, последняя строка должна быть пустой

2022-11-14 14:21 UTC, rateterin commented on tests/test_views.py
> +        print(f'***** {Post.objects.count()} всего постов из 1')
Убрать принт

2022-11-14 14:21 UTC, rateterin commented on tests/test_views.py
> +        ic(moder_gr)
Полагаю, можно убрать

2022-11-14 14:21 UTC, rateterin commented on tests/test_views.py
> +        print(f'***** {Post.objects.count()} всего постов из 6')
Убрать принт

2022-11-14 14:31 UTC, rateterin requested changes

2022-11-14 14:31 UTC, rateterin commented on tests/test_models.py
> +from django.test import TestCase, RequestFactory
Точно нужно? Не используется.

2022-11-14 14:31 UTC, rateterin commented on tests/test_models.py
> +import sys
Точно нужно? Не используется.

2022-11-14 14:31 UTC, rateterin commented on tests/test_models.py
> +from icecream import ic
Это точно нужно тут

2022-11-14 14:31 UTC, rateterin commented on tests/test_views.py
> +# endregion
Возможно, стоит убрать. icecream, возможно, не потребуется в проде. time не используется.

2022-11-14 19:16 UTC, py0trandreev commented on tests/test_models.py
> +
исправил

2022-11-14 19:22 UTC, py0trandreev commented on app/mainapp/views.py
> -
исправил

2022-11-14 19:31 UTC, py0trandreev commented on tests/test_models.py
> +
исправил

2022-11-15 19:10 UTC, rateterin approved these changes

2022-11-15 19:11 UTC, rateterin approved these changes

2022-11-15 21:46 UTC, gromovvladimir approved these changes

2022-11-15 21:47 UTC, merged